# Generated by Django 5.2.1 on 2025-05-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_task_completed_task_completed_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="creator",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="creator",
            new_name="owner",
        ),
    ]
