# Generated by Django 5.2.1 on 2025-05-20 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_creator_project_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("completed", "Depends on completion"),
                            ("not_completed", "Depends on not being completed"),
                            ("in_progress", "Depends on being in progress"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_on_me",
                        to="base.task",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_dependencies",
                        to="base.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "depends_on")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_tasks",
                through="base.TaskDependency",
                through_fields=("task", "depends_on"),
                to="base.task",
            ),
        ),
    ]
