# Generated by Django 5.2.1 on 2025-05-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_taskdependency_task_dependencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdependency",
            name="condition",
            field=models.CharField(
                choices=[
                    ("completed", "Depends on completion"),
                    ("not_completed", "Depends on not being completed"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
    ]
