# Generated by Django 5.2.1 on 2025-05-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_taskdependency_options_taskdependency_group_id_and_more"),
    ]

    operations = []
