# Generated by Django 5.2.1 on 2025-05-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_auto_20250521_2052"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="dependencies",
        ),
    ]
