# Generated by Django 5.2.1 on 2025-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_task_dependencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdependency",
            name="logic_group",
            field=models.CharField(
                choices=[
                    ("AND", "All dependencies must be satisfied"),
                    ("OR", "Any dependency must be satisfied"),
                ],
                default="DEFAULT",
                help_text="Logical operator for this dependency group",
                max_length=3,
            ),
        ),
    ]
