# Generated by Django 5.2.1 on 2025-05-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_taskdependency_logic_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskdependency",
            old_name="logic_group",
            new_name="logic",
        ),
    ]
