# Generated by Django 5.2.1 on 2025-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_rename_logic_group_taskdependency_logic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdependency",
            name="logic",
            field=models.CharField(
                choices=[
                    ("AND", "All dependencies must be satisfied"),
                    ("OR", "Any dependency must be satisfied"),
                ],
                default="AND",
                help_text="Logical operator for this dependency group",
                max_length=3,
            ),
        ),
    ]
